services:
  db:
    image: mysql:8.0
    container_name: pets-mysql
    environment:
      MYSQL_DATABASE: pets
      MYSQL_USER: pets
      MYSQL_PASSWORD: pets
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppets"]
      interval: 5s
      timeout: 3s
      retries: 10

  pets-api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pets?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: pets
      SPRING_DATASOURCE_PASSWORD: pets
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
